### ISSUE TITLE
DOC: Add clarification that this only runs on non-M1 mac machines

### ISSUE THREAD

**Issue by mgrover1** [xCDAT/xcdat-validation#51]
Validation is not currently possible on recent MacOS machines, that utilize the arm-based chips (ex. M1). This should be clarified within the README/documentation.

This is preventing some steps related to [the JOSS review](https://github.com/openjournals/joss-reviews/issues/6426) for xcdat.

**Comment by brian-rose** [comment]
I ran into the same issue -- cannot run the validation scripts on a Mac laptop (osx-arm64). 

As far as I can tell, the reason is that cdms2 is unavailable for this platform, e.g. https://anaconda.org/conda-forge/cdms2

Although this issue was closed, I don't see the limitation documented anywhere. This has slowed down my [JOSS review for xCDAT](https://github.com/openjournals/joss-reviews/issues/6426).
