### ISSUE TITLE
DOC: Include instructions on how to access the datasets used for benchmarks

### ISSUE THREAD

**Issue by mgrover1** [xCDAT/xcdat-validation#52]
To ensure reproducibility, instructions should be added on how to access datasets exclusively on LLNL resources, as with this example

https://github.com/xCDAT/xcdat-validation/blob/main/scripts/performance-benchmarks/perf_benchmark.py

This prevents full reproducibility of the results

Related to https://github.com/openjournals/joss-reviews/issues/6426

**Comment by tomvothecoder** [comment]
Hey @pochedls, are all of these [datasets](
https://github.com/xCDAT/xcdat-validation/blob/880aff7b4c754d9a920eecb895f9034fac5fc00e/scripts/performance-benchmarks/perf_benchmark.py#L92-L118) available on ESGF? If they are, I'll check if Globus links are available to make it easier to download the larger datasets. 

Also are the XML files publicly available somewhere so that non-LLNL users can open multi-file datasets with `cdms2`? Otherwise, we need to figure out another way to open multi-file datasets using `cdms2`.

**Comment by pochedls** [comment]
> Hey @pochedls, are all of these [datasets](https://github.com/xCDAT/xcdat-validation/blob/880aff7b4c754d9a920eecb895f9034fac5fc00e/scripts/performance-benchmarks/perf_benchmark.py#L92-L118) available on ESGF? If they are, I'll check if Globus links are available to make it easier to download the larger datasets.
> 
> Also are the XML files publicly available somewhere so that non-LLNL users can open multi-file datasets with `cdms2`? Otherwise, we need to figure out another way to open multi-file datasets using `cdms2`.

These datasets are all on ESGF. 

XML files are usually created locally (to map to your local files on disk). Once the data is in place, you can create xml files with `cdscan -x file.xml /path/to/dataset/` (pretty sure that is the syntax).

**Comment by tomvothecoder** [comment]
Thanks @pochedls. I'll need to update the instructions for the script so that non-LLNL users can reproduce the XMLs.
